export const STACKED_METRIC_MIN_SLOT_COUNT = 2;
export const STACKED_METRIC_MAX_SLOT_COUNT = 3;
export const STACKED_METRIC_DEFAULT_AUTO_ROTATE_ENABLED = true;
export const STACKED_METRIC_DEFAULT_INTERVAL_SECONDS = 3;
export const STACKED_METRIC_MIN_INTERVAL_SECONDS = 1;
export const STACKED_METRIC_MAX_INTERVAL_SECONDS = 5;
