import assert from "node:assert/strict";
import { test } from "vitest";
import { buildCustomMetricPrompt } from "./prompt";
import type { SampleState } from "./types";

test("Custom Metric prompt uses normal JSON samples without mentioning digests", () => {
    const prompt = buildCustomMetricPrompt({
        locale: "en",
        sourceUrl: "https://api.example.com/weather",
        userIntent: "Display temperature",
        sample: buildSampleState({
            promptSample: {
                kind: "jsonSample",
                text: "{\"temp\":23.5}",
            },
        }),
    });

    assert.match(prompt, /Input JSON sample:\n```json\n\{"temp":23\.5\}\n```/u);
    assert.match(prompt, /3\. The input sample is the fetched JSON sample\. Use it directly\./u);
    assert.match(prompt, /8\. Otherwise, write the jq filter now in exactly one fenced code block labeled jq\./u);
    assert.match(prompt, /put only the jq expression in exactly one fenced code block labeled jq/u);
    assert.doesNotMatch(prompt, /digest/iu);
});

test("Custom Metric prompt labels JSON digests and keeps digest-specific guidance isolated", () => {
    const prompt = buildCustomMetricPrompt({
        locale: "en",
        sourceUrl: "https://api.example.com/sensors",
        userIntent: "Find GPU temperature",
        sample: buildSampleState({
            responseBytes: 105000,
            promptSample: {
                kind: "jsonDigest",
                text: "{\n  \"Children\": [\n    {\"Text\":\"CPU Package\"},\n    {\"Text\":\"GPU Core\"}\n  ]\n}",
                arraySummaries: ["$.Children: 456 items; first 3 shown"],
            },
        }),
    });

    assert.match(prompt, /Input JSON digest for a large 105000-byte response:/u);
    assert.match(prompt, /Digest note:/u);
    assert.match(prompt, /Array lengths:\n- \$\.Children: 456 items; first 3 shown/u);
    assert.match(prompt, /3\. The input is a JSON digest generated by Stream Deck/u);
    assert.match(prompt, /Do not reject solely because the digest is incomplete/u);
    assert.match(prompt, /8\. Otherwise, write the jq filter now in exactly one fenced code block labeled jq\./u);
});

test("Custom Metric prompt explains capped JSON digest text", () => {
    const prompt = buildCustomMetricPrompt({
        locale: "en",
        sourceUrl: "https://api.example.com/sensors",
        userIntent: "Find GPU temperature",
        sample: buildSampleState({
            responseBytes: 105000,
            promptSample: {
                kind: "truncatedJsonDigest",
                text: "{\n  \"Children\": [",
                arraySummaries: ["$.Children: 456 items; first 3 shown"],
            },
        }),
    });

    assert.match(prompt, /```text\n\{\n {2}"Children": \[/u);
    assert.match(prompt, /The digest text itself was capped to keep this prompt bounded/u);
});

test("Custom Metric prompt rejects raw response previews instead of asking for jq", () => {
    const prompt = buildCustomMetricPrompt({
        locale: "en",
        sourceUrl: "https://api.example.com/weather",
        userIntent: "Display temperature",
        sample: buildSampleState({
            responseBytes: 12000,
            promptSample: {
                kind: "rawPreview",
                text: "{\"error\":true,\"reason\":\"Daily API request limit exceeded\"}",
                hasTruncatedInvalidJsonPreview: true,
            },
        }),
    });

    assert.match(prompt, /Input response preview:\n```text/u);
    assert.match(prompt, /3\. The input is a raw response preview, not a valid JSON sample\. Do not write jq\./u);
    assert.match(prompt, /If the response preview is an API error, summarize the error/u);
});

test("Custom Metric prompt redacts secret-like URL query values", () => {
    const prompt = buildCustomMetricPrompt({
        locale: "ja",
        sourceUrl: "https://api.example.com/weather?api_key=secret-value&city=tokyo",
        userIntent: "Display temperature",
        sample: buildSampleState({
            promptSample: {
                kind: "jsonSample",
                text: "{\"temp\":23.5}",
            },
        }),
    });

    assert.match(prompt, /api_key=REDACTED/u);
    assert.doesNotMatch(prompt, /secret-value/u);
    assert.match(prompt, /Source URL warning:/u);
    assert.match(prompt, /9\. Reply to clarification or sample-request messages in ja\./u);
});

function buildSampleState(overrides: {
    readonly responseBytes?: number;
    readonly promptSample: SampleState["promptSample"];
}): SampleState {
    return {
        url: "https://api.example.com/data",
        responseBytes: overrides.responseBytes ?? 13,
        elapsedMilliseconds: 42,
        samplePreview: "{}",
        isSamplePreviewTruncated: false,
        promptSample: overrides.promptSample,
    };
}
