import type { AsusRogMouseRouteDescriptor } from "./asus-rog-route-types";

/**
 * Known direct mouse battery paths from G-Helper model facts.
 *
 * Source: G-Helper
 * Files: app/Peripherals/Mouse/Models/*.cs
 * Commit: c0ef2cd9b5cafe8a32505137e652058a5c8fe32d
 * License: GPL-3.0
 *
 * `KNOWN` means ShoMetrics has a concrete PID, endpoint, report id, and parser
 * rule from the reference model class. This list intentionally excludes Omni
 * mouse routes until paired-device lookup is implemented; probing the generic
 * Omni mouse collection without knowing the paired PID would be broader than
 * the allowlist contract.
 */
export const ASUS_ROG_KNOWN_MOUSE_DIRECT_PID_ROUTES: readonly AsusRogMouseRouteDescriptor[] =
    [
        {
            productId: 0x18a0,
            endpointPathToken: "mi_02",
            displayName: "ROG Gladius II Wireless",
            modelId: "asus-rog-mouse:gladius-ii-wireless",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x18b4,
            endpointPathToken: "mi_01",
            displayName: "ROG Strix Carry",
            modelId: "asus-rog-mouse:strix-carry",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt7",
            reportId: 0x00,
        },
        {
            productId: 0x18e3,
            endpointPathToken: "mi_00",
            displayName: "ROG Chakram",
            modelId: "asus-rog-mouse:chakram",
            transport: "usbWired",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x18e5,
            endpointPathToken: "mi_00",
            displayName: "ROG Chakram",
            modelId: "asus-rog-mouse:chakram",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1906,
            endpointPathToken: "mi_00",
            displayName: "ROG Pugio II",
            modelId: "asus-rog-mouse:pugio-ii",
            transport: "usbWired",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1908,
            endpointPathToken: "mi_00",
            displayName: "ROG Pugio II",
            modelId: "asus-rog-mouse:pugio-ii",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1947,
            endpointPathToken: "mi_00",
            displayName: "ROG Strix Impact II Wireless",
            modelId: "asus-rog-mouse:strix-impact-ii-wireless",
            transport: "usbWired",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1949,
            endpointPathToken: "mi_00",
            displayName: "ROG Strix Impact II Wireless",
            modelId: "asus-rog-mouse:strix-impact-ii-wireless",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x195e,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris Wireless",
            modelId: "asus-rog-mouse:keris-wireless",
            transport: "usbWired",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1960,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris Wireless",
            modelId: "asus-rog-mouse:keris-wireless",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1977,
            endpointPathToken: "mi_00",
            displayName: "ROG Spatha X",
            modelId: "asus-rog-mouse:spatha-x",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1979,
            endpointPathToken: "mi_00",
            displayName: "ROG Spatha X",
            modelId: "asus-rog-mouse:spatha-x",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x197d,
            endpointPathToken: "mi_00",
            displayName: "ROG Gladius III Wireless",
            modelId: "asus-rog-mouse:gladius-iii-wireless",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x197f,
            endpointPathToken: "mi_00",
            displayName: "ROG Gladius III Wireless",
            modelId: "asus-rog-mouse:gladius-iii-wireless",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x19f4,
            endpointPathToken: "mi_00",
            displayName: "TUF Gaming M4 Wireless",
            modelId: "asus-tuf-mouse:m4-wireless",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a18,
            endpointPathToken: "mi_00",
            displayName: "ROG Chakram X",
            modelId: "asus-rog-mouse:chakram-x",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a1a,
            endpointPathToken: "mi_00",
            displayName: "ROG Chakram X",
            modelId: "asus-rog-mouse:chakram-x",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a57,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris EVA Edition",
            modelId: "asus-rog-mouse:keris-wireless-eva-edition",
            transport: "usbWired",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a59,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris EVA Edition",
            modelId: "asus-rog-mouse:keris-wireless-eva-edition",
            transport: "usbReceiver",
            parserKind: "quarterPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a66,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris Wireless Aimpoint",
            modelId: "asus-rog-mouse:keris-wireless-aimpoint",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a68,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris Wireless Aimpoint",
            modelId: "asus-rog-mouse:keris-wireless-aimpoint",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a70,
            endpointPathToken: "mi_00",
            displayName: "ROG Gladius III Aimpoint",
            modelId: "asus-rog-mouse:gladius-iii-aimpoint",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a72,
            endpointPathToken: "mi_00",
            displayName: "ROG Gladius III Aimpoint",
            modelId: "asus-rog-mouse:gladius-iii-aimpoint",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a8d,
            endpointPathToken: "mi_00",
            displayName: "TX Gaming Mouse",
            modelId: "asus-tx-mouse:gaming-wireless",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a92,
            endpointPathToken: "mi_00",
            displayName: "ROG Harpe Ace Aim Lab Edition",
            modelId: "asus-rog-mouse:harpe-ace-aim-lab-edition",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1a94,
            endpointPathToken: "mi_00",
            displayName: "ROG Harpe Ace Aim Lab Edition",
            modelId: "asus-rog-mouse:harpe-ace-aim-lab-edition",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1ad0,
            endpointPathToken: "mi_02&col03",
            displayName: "ROG Harpe II Ace",
            modelId: "asus-rog-mouse:harpe-ii-ace",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x03,
        },
        {
            productId: 0x1af3,
            endpointPathToken: "mi_00",
            displayName: "TX Gaming Mini",
            modelId: "asus-tx-mouse:gaming-mini",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1af5,
            endpointPathToken: "mi_00",
            displayName: "TX Gaming Mini",
            modelId: "asus-tx-mouse:gaming-mini",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1b0a,
            endpointPathToken: "mi_00",
            displayName: "ROG Gladius III Eva 2",
            modelId: "asus-rog-mouse:gladius-iii-eva-2",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1b0c,
            endpointPathToken: "mi_00",
            displayName: "ROG Gladius III Eva 2",
            modelId: "asus-rog-mouse:gladius-iii-eva-2",
            transport: "usbReceiver",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1b16,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris II Ace",
            modelId: "asus-rog-mouse:keris-ii-ace",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1b63,
            endpointPathToken: "mi_00",
            displayName: "ROG Harpe Ace Mini",
            modelId: "asus-rog-mouse:harpe-ace-mini",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1b67,
            endpointPathToken: "mi_00",
            displayName: "ROG Harpe Ace Extreme",
            modelId: "asus-rog-mouse:harpe-ace-extreme",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1c0c,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris II Origin",
            modelId: "asus-rog-mouse:keris-ii-origin",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1c69,
            endpointPathToken: "mi_00",
            displayName: "ROG Harpe II Ace",
            modelId: "asus-rog-mouse:harpe-ii-ace",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
        {
            productId: 0x1d4c,
            endpointPathToken: "mi_00",
            displayName: "ROG Keris II Origin KJP",
            modelId: "asus-rog-mouse:keris-ii-origin-kjp",
            transport: "usbWired",
            parserKind: "rawPercentAt5",
            reportId: 0x00,
        },
    ];
