export type {
    ActionKind,
    CircleStyle,
    ColorMode,
    DiskMetricKind,
    DiskThroughputDirection,
    DiskUsageDisplayMode,
    GraphicStyle,
    GraphicType,
    GridLineType,
    GridLineVisibility,
    NetworkDirection,
    NetworkTrafficDisplayMode,
    NetworkUnitBase,
    ScaleMode,
    TemperatureUnit,
} from "../../settings/widget-settings";
