export const inspectorScope = {
    cpuUsageCircularScope: "cpu-usage.circular",
    cpuUsageLinearScope: "cpu-usage.linear",
    cpuUsageSparklineScope: "cpu-usage.sparkline",
    ramCircularScope: "ram.circular",
    ramLinearScope: "ram.linear",
    ramSparklineScope: "ram.sparkline",
    diskUsageCircularScope: "disk.usage.circular",
    diskUsageLinearScope: "disk.usage.linear",
    diskUsageSparklineScope: "disk.usage.sparkline",
    diskThroughputCircularScope: "disk.throughput.circular",
    diskThroughputLinearScope: "disk.throughput.linear",
    diskThroughputSparklineScope: "disk.throughput.sparkline",
    netSpeedCircularScope: "net-speed.circular",
    netSpeedLinearScope: "net-speed.linear",
    netSpeedSparklineScope: "net-speed.sparkline",
    gpuUsageCircularScope: "gpu-usage.circular",
    gpuUsageLinearScope: "gpu-usage.linear",
    gpuUsageSparklineScope: "gpu-usage.sparkline",
    gpuTempCircularScope: "gpu-temp.circular",
    gpuTempLinearScope: "gpu-temp.linear",
    gpuTempSparklineScope: "gpu-temp.sparkline",
    gpuVramCircularScope: "gpu-vram.circular",
    gpuVramLinearScope: "gpu-vram.linear",
    gpuVramSparklineScope: "gpu-vram.sparkline",
    gpuPowerCircularScope: "gpu-power.circular",
    gpuPowerLinearScope: "gpu-power.linear",
    gpuPowerSparklineScope: "gpu-power.sparkline",
    unknownScope: "unknown",
} as const;

export type InspectorScope = typeof inspectorScope[keyof typeof inspectorScope];
